# Generated by Django 3.2 on 2021-05-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maskdetector',
            name='person_has_mask',
            field=models.BooleanField(default=False),
        ),
    ]
